package kge.api.editor

enum class EditorSelectionGizmoAxis {
    TRANSLATE_CENTER,
    TRANSLATE_X, TRANSLATE_Y, TRANSLATE_Z,
    TRANSLATE_PLANE_XY, TRANSLATE_PLANE_XZ, TRANSLATE_PLANE_ZY,

    ROTATE_CENTER,
    ROTATE_X, ROTATE_Y, ROTATE_Z,

    SCALE_CENTER,
    SCALE_X, SCALE_Y, SCALE_Z
}